name: Update THM Badge

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Profile Badge
        run: |
          curl -s https://amazonaws.com -o thm-badge.png
          
      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add thm-badge.png
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update TryHackMe Badge" && git push)

      - name: Prevent Workflow Inactivity Timeout
        if: github.event_name == 'schedule'
        uses: liskin/gh-workflow-keepalive@v1
